### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by venixdev** [ordinall/BetterDiscord-Stuff#1]
I downloaded the newest version via the pl lib, but when i ask a friend to start a party and i click on the join button my spotify client only blinks in the taskbar, but it wont play the song :(

**Comment by ordinall** [comment]
that's strange, what do you mean by pl lib?

**Comment by venixdev** [comment]
sry, plugin repo it just a plugin btw

**Comment by venixdev** [comment]
but if you accept my fa on discord i can show you

**Comment by venixdev** [comment]
maybe i need to connect my spotify to discord or its because of spicetify

**Comment by ordinall** [comment]
Yeah, you do need to connect your Spotify account to discord. Discord uses the Spotify API and your access token to pause/play songs on Spotify.

**Comment by advikkabra** [comment]
i have this same issue as well

**Comment by ordinall** [comment]
@advikkabra Is your Spotify account connected to discord?

**Comment by venixdev** [comment]
I reconnected my Spotify and it worked!
