### ISSUE TITLE
No longer works. 

### ISSUE THREAD

**Issue by LegendaryITA** [ordinall/BetterDiscord-Stuff#12]

**Comment by ordinall** [comment]
Works for me and my friends, and not enough information provided.

**Comment by LegendaryITA** [comment]
OK so, when my friend and I putted the plugins, activated it and restarted
Discord, we tried to "Listen Together" in Spotify, in fact I tried to click
"Listen Together" button in his profile, but it didn't work.

Il giorno dom 24 apr 2022 alle ore 02:02 Abdullah Abid Ansari <
***@***.***> ha scritto:

**Comment by ordinall** [comment]
Do you both have your spotify account connected to discord ? and spotify is open? do you have ZeresPluginLibrary installed ?
could you  open the console by pressing ctrl+shift+i, and write

`ZLibrary.DiscordModules.DeviceStore.getProfile()`

press enter, and then write

`ZLibrary.WebpackModules.getByProps("isSpotifyPremium").isSpotifyPremium()`

and press enter and show me the output?

**Comment by ordinall** [comment]
closing due to no response and inactivity
