### ISSUE TITLE
[DisableStickerSuggestions] Switch tile doesn't work

### ISSUE THREAD

**Issue by vilchu** [ordinall/BetterDiscord-Stuff#14]
Every time I press the switch tile it just slides back to off, the plugin works though 

![2022-05-21_jYwD](https://user-images.githubusercontent.com/55512609/169618682-e714fbc4-0632-4491-8776-49f27009743c.gif)

Also turns off everytime reloading Discord

I don't know if this is because I'm using Powercord bdCompat or what, but just wanted to mention.

**Comment by reynoldyehezkiel** [comment]
i got this error toast message when i turn it on
![image](https://user-images.githubusercontent.com/73789263/169716735-990f8bfa-517f-4798-865e-1c889462e5fd.png)

**Comment by ordinall** [comment]
i am aware of this issue, it happened because of an update of discord. It will take a few days to fix since i am busy.

**Comment by SilverSix311** [comment]
Can I ask if you know what this might be in the code? My friend and I are trying to look into it ourselves. He knows a bit of js, I know nothing but trying to learn. We both know code logic tho. I'm a systems engineer personally. Just trying to figure out where I should be looking so I can help.

**Comment by ordinall** [comment]
fixed in [14c7486](https://github.com/ordinall/BetterDiscord-Stuff/commit/14c7486afe8671ca28f91e53c683abd2c1551e73)
