### ISSUE TITLE
Spotify album art and title does not appear

### ISSUE THREAD

**Issue by Nicaus** [ordinall/BetterDiscord-Stuff#15]
![Screenshot 2022-06-25 005200](https://user-images.githubusercontent.com/42901709/175758505-9ed81195-7a59-480b-bafe-e2a6c46ad2e3.png)

**Comment by ordinall** [comment]
I seriously doubt that the plugin is the source of this problem. It only tricks discord into thinking you have a premium account and thats it. Discord manages all the song playing and pausing. Try updating or restarting your spotify.
