### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by splitparadcx** [ordinall/BetterDiscord-Stuff#17]
Whenever I try opening it to copy it into the plugin folder from discord this error message pops up

![image](https://user-images.githubusercontent.com/106204755/182190850-2b3debfa-afa5-447b-a2ec-a9fd3c8ab50c.png)

**Comment by ordinall** [comment]
my plugin doesn't implement the "open to put it into plugin's folder" thing. You have to manually put the .js file in the BD plugin folder. Also, redownload the file. I just fixed a bug in the plugin.
