### ISSUE TITLE
Plugin does not start

### ISSUE THREAD

**Issue by TimeToCry** [ordinall/BetterDiscord-Stuff#18]
When i try to turn on the plugin it doesn't load up 
![image](https://user-images.githubusercontent.com/71668687/182268037-c529b00d-d577-42d8-b8f6-a9a55ccd7d7c.png)

**Comment by TimeToCry** [comment]
this is just a small cropped screenshot I have zerespluginlibrary installed

**Comment by Fremontcat0607** [comment]
same

**Comment by rakuzen25** [comment]
Can reproduce. BD version `1.5.3-Hotfix`.

**Comment by Shanks1940** [comment]
doesnt work F

**Comment by ronfino** [comment]
![image](https://user-images.githubusercontent.com/77462428/182317152-3c949c86-7397-4314-9640-988661da57be.png)
same issue

**Comment by Nithyen** [comment]
Bruh it doesnt work

**Comment by eshaane** [comment]
There's a hot fix I made on my github

**Comment by Nithyen** [comment]
Ok

**Comment by ordinall** [comment]
fixed in [466a378](https://github.com/ordinall/BetterDiscord-Stuff/commit/466a37895b8d2d541ac1d7e4788a3a78abbe41be), restart discord, you should get the update notification on top of the window
