### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Pixelhunter33** [ordinall/BetterDiscord-Stuff#2]
When I try listen along with someone else it still tells me I need to buy premium...

**Comment by ordinall** [comment]
Is the plugin enabled in the BD plugin settings?

**Comment by marcpinet** [comment]
yes it is, and doesn't work

**Comment by ordinall** [comment]
Do you have any other plugins which are related to Spotify? Do you have ZeresPluginLibrary installed? If yes, then play any song in spotify, press ctrl+shift+i and go to console and paste:
`BdApi.findModuleByProps("isSpotifyPremium").isSpotifyPremium()`
and press enter, then send a screenshot here.

**Comment by marcpinet** [comment]
![image](https://user-images.githubusercontent.com/52708150/124394419-b5cfd580-dcff-11eb-80d7-d2420cd78dee.png)

**Comment by ordinall** [comment]
wait, I just saw that you are not issue author, @marcpinet , are you having the same issue as the author ?

**Comment by marcpinet** [comment]
> wait, I just saw that you are not issue author, @marcpinet , are you having the same issue as the author ?

yes

**Comment by ordinall** [comment]
can you also type this in console and tell me the output ?
`ZeresPluginLibrary.DiscordModules.DeviceStore.getProfile(123)`

**Comment by MrinalSh** [comment]
->ZeresPluginLibrary.DiscordModules.DeviceStore.getProfile(123)


->undefined

**Comment by ordinall** [comment]
Multiple people replying on troubleshooting steps don't help the problem. Well, the plugin seems to be working fine. It is patching the functions needed to be patched. Try reconnecting your Spotify account with discord.

**Comment by modkavartini** [comment]
I decided to try this plugin out and I'm having the same problem as well
> 
> 
> Do you have any other plugins which are related to Spotify? Do you have ZeresPluginLibrary installed? If yes, then play any song in spotify, press ctrl+shift+i and go to console and paste:
> `BdApi.findModuleByProps("isSpotifyPremium").isSpotifyPremium()`
> and press enter, then send a screenshot here.

![image](https://user-images.githubusercontent.com/81793953/128605416-f0f6836e-e487-4226-914d-ac79163957db.png)



> 
> 
> can you also type this in console and tell me the output ?
> `ZeresPluginLibrary.DiscordModules.DeviceStore.getProfile(123)`

![image](https://user-images.githubusercontent.com/81793953/128605492-d9496ece-e48c-4119-89c5-eb554153ba0d.png)

**Comment by ordinall** [comment]
@ModkaVartini The plugin doesn't seem to be enabled. Double-check that you have the plugin enabled.

**Comment by modkavartini** [comment]
> 
> 
> @ModkaVartini The plugin doesn't seem to be enabled. Double-check that you have the plugin enabled.

It is enabled, ZeresPluginLibrary is installed as well, don't see what I could be doing wrong.
The support in the official BetterDiscord server sucks btw

**Comment by modkavartini** [comment]
Update: I opened discord today and gave it another go when @ordinall reached out to me in my dms (props to him for actually caring) and now it works like a charm! I haven't the slightest idea as to how it did, but I like to think a restart is what fixed it.

**Comment by ordinall** [comment]
Since the original issue creator has been inactive for really long, i am gonna close this issue, if someone gets a similar problem, they can make a new issue.
