### ISSUE TITLE
When listen along host skips song the progress on the last song is carried over

### ISSUE THREAD

**Issue by Tae47** [ordinall/BetterDiscord-Stuff#21]
If the song currently playing is at 1 minute of progress and it is skipped by the host, the next song playing will start at the 1-minute mark instead of starting at the beginning.

**Comment by Florian-Mahlberg** [comment]
Can't reproduce anymore - seems to be fixed with the new update?

**Comment by Florian-Mahlberg** [comment]
@d0gkiller87  can you reproduce it?

**Comment by ordinall** [comment]
Can't reproduce. Song syncing is the responsibility of discord and the plugin doesn't even touch that. It only spoofs premium status which should not effect any other thing. Try
- Reconnecting spotify account
- Updating spotify
