### ISSUE TITLE
[SpotifyListenAlong] meta not found

### ISSUE THREAD

**Issue by firingthoughts** [ordinall/BetterDiscord-Stuff#30]
I downloaded "listen along to spotify" from better discord plugins website, it wouldnt work (spotify application opens on windows but doesnt play or show the song) so i downloaded the github version, now it just says meta not found

**Comment by firingthoughts** [comment]
never mind, it's just incompatible with spotify controls by devilbro also being installed -- redownloaded it from the website not here

**Comment by Ecologist7032** [comment]
@firingthoughts  Hey, has the issue with Spotify opening up been fixed now? I'm facing the same issue, and if it has been resolved, could you please let me know how you fixed it? Thnaks

**Comment by firingthoughts** [comment]
i've already posted the solution above you, you have to delete the plugin, redownload it form the BetterDiscord plugins website not from github. Works for me now

**Comment by firingthoughts** [comment]
> @firingthoughts Hey, has the issue with Spotify opening up been fixed now? I'm facing the same issue, and if it has been resolved, could you please let me know how you fixed it? Thnaks

i've already posted the solution above you, you have to delete the plugin, redownload it form the BetterDiscord plugins website not
