### ISSUE TITLE
Settings will not open.

### ISSUE THREAD

**Issue by MagmaSlime123** [ordinall/BetterDiscord-Stuff#31]
Title.

![Screenshot 2023-03-27 003648](https://user-images.githubusercontent.com/51277766/227860105-a3e09f0e-a962-4f2c-8f35-7c1b5a6f45d8.png)

**Comment by ordinall** [comment]
that plugin has been outdated for quite a while, does need an update to comply with new settings panel thing in BD but i unfortunately am busy in my final year project right now. I will update it, but no ETA.

**Comment by MagmaSlime123** [comment]
If Sticker Suggestions is outdated, you should probably remove it, or give it to others if you don't plan on continuing it.

**Comment by ordinall** [comment]
Removed it
