### ISSUE TITLE
[SpotifyListenAlong] audio issue

### ISSUE THREAD

**Issue by Flyingbacen** [ordinall/BetterDiscord-Stuff#32]
I was previously _(failing)_ to use this plugin on linux, and on both distributions I tested, (Holoiso and Mint Mate), the audio is constantly jittery. 
I reinstalled Windows, reinstalled betterdiscord and this plugin, and it worked fine. would this be an issue with the plugin, discord, or Spotify? possibly all three?

**Comment by ordinall** [comment]
Sounds like a spotify issue or discord, the plugin just tricks discord into thinking that the user is premium, all the other stuff is handled by discord and spotify themselves.
