### ISSUE TITLE
How this plugin works?

### ISSUE THREAD

**Issue by Neferet-0** [ordinall/BetterDiscord-Stuff#34]
Once activated, and Spotify is launched with music playing, nothing happens on discord.

Do we need to have “**activities status**” enabled in the discord settings, for the plugin to work? _(For my part it is disabled, I do not necessarily want to have displayed everything I do)_.

**Comment by ordinall** [comment]
I do not think activity status will effect spotify listen along feature. If you listen along someone and spotify launches with song playing, then i think its working as intended? please clarify more. Is the music working? is it synced to the person you are listening along?

**Comment by Neferet-0** [comment]
Hmm, does it only work by listening on other people?
Does it also work on ourselves?, because nothing changes on us.

(I haven't had time to test with someone else yet)

**Comment by Neferet-0** [comment]
I just tried with a person, the music starts well _(after a few Spotify ads)_ but it is not synchronized with the people I am listening to.

**Comment by ordinall** [comment]
This just allows you to listen along someone without premium. Also, it not being synchronized might be you pressing the wrong button, can you confirm you are pressing the correct button for listen along, refer to this picture:

![image](https://github.com/ordinall/BetterDiscord-Stuff/assets/49290918/2d2791d2-9535-4b20-8256-16900402765e)

**Comment by Neferet-0** [comment]
Hmm no, I wasn't on that button, when I try, the button is loading, but nothing happens. (In Spotify and Discord)

**Comment by ordinall** [comment]
Not sure dude, it is working for me. Try restarting discord, make sure betterdiscord is working.

**Comment by Neferet-0** [comment]
I already tried :/

I restarted discord,
Disabled/enabled the plugin
Repair BetterDiscord (just in case)
Close/open Spotify
Shut down the pc and restart it.

Despite that, nothing happens on my side, the button load, but nothing more.
