### ISSUE TITLE
Listen along 0 seconds

### ISSUE THREAD

**Issue by whitetux123** [ordinall/BetterDiscord-Stuff#35]
For some reason whenever I try to listen along with a friend, in spotify it shows me what song they're playing and it updates when they skip, but for some reason for every song it just stays at 0 seconds and doesn't play. If i play it myself, I am not in sync with the other person, and the second they skip to the next song, it goes back to staying at 0 seconds.

**Comment by CyberBonk** [comment]
same issue

**Comment by LavenderAndChamomile** [comment]
For me, I got nothing on my end....no option to use it at all.

**Comment by ordinall** [comment]
plugin just fakes premium status, the actual listening along is performed by discord itself so i doubt the plugin is causing any issues there, please try reconnecting spotify or restarting discord and spotify
