### ISSUE TITLE
Play along button gets stuck in loading "[...]"

### ISSUE THREAD

**Issue by PinkyPromises** [ordinall/BetterDiscord-Stuff#36]
Title

**Comment by MangoRox** [comment]
+1

**Comment by ochen1** [comment]
Actually, the button isn't working for those with premium either.

**Comment by GodzillasFeet** [comment]
pleaseee fix this 🙏

**Comment by marto05** [comment]
It just doesn't work

**Comment by aryxenv** [comment]
this!!

**Comment by Av1lly** [comment]
+1

**Comment by Zauzzx** [comment]
Its still doesn't work

**Comment by ochen1** [comment]
It's been fixed. Make sure to restart Discord to automatically update. If it still doesn't work, try downloading the official Public Test Build version of Discord.

**Comment by ochen1** [comment]
Also available at https://ptb.discord.com/

**Comment by ordinall** [comment]
Sorry guys, I am too busy at work :/. @ochen1 if it fixed itself, it was probably discord changing some stuff, and then changing it back. I'll try looking into it. Please notify if it works fine now
