### ISSUE TITLE
[Visual Bug] The "Play along" button disappeared when the song's name is too long

### ISSUE THREAD

**Issue by mohamedamara1** [ordinall/BetterDiscord-Stuff#38]
The button disappeared as you can see when the song's name is too long

![image](https://github.com/ordinall/BetterDiscord-Stuff/assets/53430360/b1240fd1-ffea-46b7-992d-971effa3b4b5)

**Comment by ordinall** [comment]
That looks like a discord issue, this plugin does not change the button visually
