### ISSUE TITLE
0PluginLibrary.plugin.js Meta not found

### ISSUE THREAD

**Issue by koreandrilla** [ordinall/BetterDiscord-Stuff#39]
When I try to download the plugin I get brought to Meta not found?
![image](https://github.com/user-attachments/assets/fd879b71-0ea1-4420-9b52-58868993e9d3)

**Comment by Pdada1** [comment]
Just looking through the code, it seems all that's changed is the person who made this library has changed their name so the link to the repo for this plugin library is changed

**Comment by Pdada1** [comment]
I managed to fix it
U need to change the require ("request").get(<url>) in the plugin js file to "https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js"
then it works
![image](https://github.com/user-attachments/assets/1b4463ad-9dea-4b6d-a030-4effe8ab2d7f)

**Comment by ordinall** [comment]
Thank you pdada1, fixed in 568a0d7 update should be available in bd soon
