### ISSUE TITLE
Other text areas still have the suggestion button

### ISSUE THREAD

**Issue by Farcrada** [ordinall/BetterDiscord-Stuff#5]
https://github.com/ordinall/BetterDiscord-Stuff/blob/1de094e48aa400fdba5979b23afe47ee69b906c1/Plugins/DisableStickerSuggestions/DisableStickerSuggestions.plugin.js#L107-L109

To fix this simply repeat the above for the `NativeTextAreaContextMenu` module.

**Comment by ordinall** [comment]
Thank you for the fix, problem is fixed in 1366694b4b3cfc29e5c71a6474a805f1cac902fd
