### ISSUE TITLE
[BUG] DisableStickerSuggestions: Does not remove keybind

### ISSUE THREAD

**Issue by Merith-TK** [ordinall/BetterDiscord-Stuff#6]
If you press ctrl+s it will still open the sticker menu

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/127897884-e8ceed6f-f7f7-4d59-b8fb-d2a102115aa6.png)

**Comment by ordinall** [comment]
This is by design. The plugin is for disabling the **suggestions** in the chatbox. It is not for removing stickers entirely from discord. You can still send stickers if you want to from the menu, but the suggestions won't nag you while you type an emote or a message.
