### ISSUE TITLE
Song time ahead

### ISSUE THREAD

**Issue by XeslanaZee** [ordinall/BetterDiscord-Stuff#7]
Every time when I am listening along the song time starts at 46 seconds. Every skip causes the same issue to happen. I didnt see any issue posted for this. 
Thanks in advance.

**Comment by ordinall** [comment]
The plugin doesn't handle playing the song or song timings. Those are handled by discord itself. It only fakes the Spotify premium status on the client-side so discord does not restrict playing the song. So, this song time problem is related to discord and not the plugin. You can try reinstalling discord or disabling all plugins related to Spotify i.e. SpotifyControls and see if it resolves your issue.
